spring:
  graphql:
    graphiql.enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      ddl-auto: create-drop
    show_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:8080/"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8888
